// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 28/02/2025 11:23:33
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/yaronecohen/Desktop/ElenaBeauty/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/yaronecohen/Desktop/ElenaBeauty/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/yaronecohen/Desktop/ElenaBeauty/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/yaronecohen/Desktop/ElenaBeauty/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/yaronecohen/Desktop/ElenaBeauty/plugins/**/*.{js,ts,mjs}","/Users/yaronecohen/Desktop/ElenaBeauty/composables/**/*.{js,ts,mjs}","/Users/yaronecohen/Desktop/ElenaBeauty/utils/**/*.{js,ts,mjs}","/Users/yaronecohen/Desktop/ElenaBeauty/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/yaronecohen/Desktop/ElenaBeauty/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/yaronecohen/Desktop/ElenaBeauty/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;